

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class Pertemuan_6 extends javax.swing.JFrame {
    java.util.List<String> daftarPesanan = new java.util.ArrayList<>();
    int totalBiaya = 0;
    /**
     * Creates new form Pertemuan_6
     */
    public Pertemuan_6() {
        initComponents();
        
        java.time.LocalDate date = java.time.LocalDate.now();
        tanggal_field.setText(date.toString());
        dropdown_kasir.addItem("Malinda");
        dropdown_kasir.addItem("Fitri");
        dropdown_kategori.addItem("Makanan");
        dropdown_kategori.addItem("Minuman");
        dropdown_kategori.addItem("Snack");
    }
    
    private void bersihkanLayar() {
        nomeja_field.setText("");
        pelanggan_field.setText("");
        jumlah_field.setText("");
        bayar_field.setText("");
        kembalian_field.setText("");
        list_menu.clearSelection();
        dropdown_kategori.setSelectedIndex(0);
    
        daftarPesanan.clear();
        totalBiaya = 0;
    
        nomeja_field.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cash_radio = new javax.swing.JRadioButton();
        transfer_radio = new javax.swing.JRadioButton();
        pesan_button = new javax.swing.JButton();
        nomeja_field = new javax.swing.JTextField();
        dropdown_kategori = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_menu = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pelanggan_field = new javax.swing.JTextField();
        tambah_button = new javax.swing.JButton();
        total_button = new javax.swing.JButton();
        tanggal_field = new javax.swing.JTextField();
        dropdown_kasir = new javax.swing.JComboBox<>();
        kembalian_field = new javax.swing.JTextField();
        bayar_field = new javax.swing.JTextField();
        jumlah_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RASA RASAN CAFE'");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. Meja ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pelanggan ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kategori ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Menu ");

        buttonGroup1.add(cash_radio);
        cash_radio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cash_radio.setForeground(new java.awt.Color(255, 255, 255));
        cash_radio.setText("CASH");

        buttonGroup1.add(transfer_radio);
        transfer_radio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        transfer_radio.setForeground(new java.awt.Color(255, 255, 255));
        transfer_radio.setText("TRANSFER");

        pesan_button.setBackground(new java.awt.Color(0, 204, 0));
        pesan_button.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        pesan_button.setText("PESAN");
        pesan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan_buttonActionPerformed(evt);
            }
        });

        nomeja_field.setBackground(new java.awt.Color(0, 204, 204));
        nomeja_field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nomeja_field.setForeground(new java.awt.Color(255, 255, 255));

        dropdown_kategori.setBackground(new java.awt.Color(0, 204, 204));
        dropdown_kategori.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dropdown_kategori.setForeground(new java.awt.Color(255, 255, 255));
        dropdown_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        dropdown_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown_kategoriActionPerformed(evt);
            }
        });

        list_menu.setBackground(new java.awt.Color(0, 204, 204));
        list_menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        list_menu.setForeground(new java.awt.Color(255, 255, 255));
        list_menu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(list_menu);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jumlah ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bayar ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kembalian");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kasir");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tanggal");

        pelanggan_field.setBackground(new java.awt.Color(0, 204, 204));
        pelanggan_field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pelanggan_field.setForeground(new java.awt.Color(255, 255, 255));

        tambah_button.setBackground(new java.awt.Color(255, 153, 0));
        tambah_button.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        tambah_button.setText("TAMBAH");
        tambah_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_buttonActionPerformed(evt);
            }
        });

        total_button.setBackground(new java.awt.Color(255, 0, 0));
        total_button.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        total_button.setText("TOTAL");
        total_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_buttonActionPerformed(evt);
            }
        });

        tanggal_field.setBackground(new java.awt.Color(0, 204, 204));
        tanggal_field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tanggal_field.setForeground(new java.awt.Color(255, 255, 255));

        dropdown_kasir.setBackground(new java.awt.Color(0, 204, 204));
        dropdown_kasir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dropdown_kasir.setForeground(new java.awt.Color(255, 255, 255));
        dropdown_kasir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        dropdown_kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown_kasirActionPerformed(evt);
            }
        });

        kembalian_field.setBackground(new java.awt.Color(0, 204, 204));
        kembalian_field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kembalian_field.setForeground(new java.awt.Color(255, 255, 255));

        bayar_field.setBackground(new java.awt.Color(0, 204, 204));
        bayar_field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bayar_field.setForeground(new java.awt.Color(255, 255, 255));

        jumlah_field.setBackground(new java.awt.Color(0, 204, 204));
        jumlah_field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jumlah_field.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cash_radio)
                        .addContainerGap(472, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(transfer_radio))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dropdown_kategori, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nomeja_field, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pelanggan_field)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kembalian_field, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(39, 39, 39)
                                        .addComponent(dropdown_kasir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(tanggal_field))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(bayar_field, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(15, 15, 15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jumlah_field, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(167, 167, 167)
                                        .addComponent(tambah_button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(total_button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pesan_button)))
                                .addContainerGap(22, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(176, 176, 176))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeja_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(dropdown_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(tanggal_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(pelanggan_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dropdown_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(bayar_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kembalian_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlah_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(23, 23, 23)
                        .addComponent(cash_radio)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transfer_radio)
                            .addComponent(tambah_button)
                            .addComponent(total_button)
                            .addComponent(pesan_button))
                        .addGap(66, 66, 66))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropdown_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown_kategoriActionPerformed
        String kategori = dropdown_kategori.getSelectedItem().toString();
        String[] data = null;

        if (kategori.equals("Makanan")) {
            data = new String[]{"Mie Bolognese - 25000", "Bakso - 15000", "Nasi Goreng - 20000", "Nasi Ayam Lava - 25000", "Nasi Bakar - 15000"};
        } else if (kategori.equals("Minuman")) {
            data = new String[]{"Matcha Latte - 20000", "Choco Oreo - 20000", "Cappucino - 20000", "Lemon Tea - 15000", "Snow Mojito - 15000"};
        } else if (kategori.equals("Snack")) {
            data = new String[]{"Dimsum - 12000", "Onion Ring - 12000", "Frensh Fries - 10000", "Pancake - 15000", "Croffle - 15000"};
        }
        list_menu.setListData(data);
    }//GEN-LAST:event_dropdown_kategoriActionPerformed

    private void pesan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan_buttonActionPerformed
        String txtBayar = bayar_field.getText();
        if (daftarPesanan.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Belum ada pesanan!");
        } else if (txtBayar.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Masukkan nominal pembayaran!");
        } else {
            int uangBayar = Integer.parseInt(txtBayar);

            if (uangBayar < totalBiaya) {
                javax.swing.JOptionPane.showMessageDialog(this, "Uang kurang! Total: Rp " + totalBiaya);
            } else {
                int kembalian = uangBayar - totalBiaya;
                kembalian_field.setText(String.valueOf(kembalian));

                String metode = cash_radio.isSelected() ? "CASH" : "TRANSFER";
                String listMenuStruk = String.join("\n", daftarPesanan);

                String struk = "      --- STRUK PESANAN ---\n" +
                       "------------------------------------------\n" +
                       "Pelanggan : " + pelanggan_field.getText() + "\n" +
                       "Metode    : " + metode + "\n" +
                       "Tanggal   : " + tanggal_field.getText() + "\n" + // <-- GANTI .getName() JADI .getText()
                       "------------------------------------------\n" +
                       "PESANAN:\n" + listMenuStruk + "\n" +
                       "------------------------------------------\n" +
                       "TOTAL       : Rp " + totalBiaya + "\n" +
                       "BAYAR       : Rp " + uangBayar + "\n" +
                       "KEMBALIAN   : Rp " + kembalian + "\n" +
                       "------------------------------------------";

                javax.swing.JOptionPane.showMessageDialog(this, struk);
        
                bersihkanLayar();
            
                java.time.LocalDate date = java.time.LocalDate.now();
                tanggal_field.setText(date.toString());
            }
        }
    }//GEN-LAST:event_pesan_buttonActionPerformed

    private void tambah_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_buttonActionPerformed
        String selectedMenu = (String) list_menu.getSelectedValue();
        String txtJumlah = jumlah_field.getText();

        if (selectedMenu == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih menu dulu!");
        } else if (txtJumlah.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Isi jumlah pesanan!");
        } else {
            String[] parts = selectedMenu.split(" - ");
            int harga = Integer.parseInt(parts[1]);
            int jumlah = Integer.parseInt(txtJumlah);
        
            int subTotal = harga * jumlah;
        
            daftarPesanan.add(parts[0] + " (x" + jumlah + ") - Rp " + subTotal);
            totalBiaya += subTotal;
 
            jumlah_field.setText("");
            list_menu.clearSelection();
            javax.swing.JOptionPane.showMessageDialog(this, parts[0] + " ditambahkan.");
        }
    }//GEN-LAST:event_tambah_buttonActionPerformed

    private void total_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_buttonActionPerformed
        if (daftarPesanan.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Belum ada pesanan yang ditambah!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Total Biaya Saat Ini: Rp " + totalBiaya);

            bayar_field.requestFocus();
        }
    }//GEN-LAST:event_total_buttonActionPerformed

    private void dropdown_kasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown_kasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdown_kasirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pertemuan_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pertemuan_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pertemuan_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pertemuan_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pertemuan_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar_field;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cash_radio;
    private javax.swing.JComboBox<String> dropdown_kasir;
    private javax.swing.JComboBox<String> dropdown_kategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah_field;
    private javax.swing.JTextField kembalian_field;
    private javax.swing.JList<String> list_menu;
    private javax.swing.JTextField nomeja_field;
    private javax.swing.JTextField pelanggan_field;
    private javax.swing.JButton pesan_button;
    private javax.swing.JButton tambah_button;
    private javax.swing.JTextField tanggal_field;
    private javax.swing.JButton total_button;
    private javax.swing.JRadioButton transfer_radio;
    // End of variables declaration//GEN-END:variables
}
